### ISSUE TITLE
"ipmitools  chassis power status "  cmd report error！

### ISSUE THREAD

**Issue by linlin4426** [openbmc/x86-power-control#3]
Hi，i build the newest openbmc version for meta-s2600wf(commit ID 
 c549f3a7f5496ec3b54ed65c8b4d8351db10995e)，which use x86-power-control  version f61ca6fdcc52beba485e014b5fad38a9e9a555ad.  But when i use "ipmitools chassis power status" commond to get  my host status, it point out "Get Chassis Power Status failed: Unspecified error",  journalctl -f command refer to "ipmid[279]: Failed to fetch ACBoot property,  ipmid[279]: Failed to fetch RestartCause property".  It seems that  phosphor-ipmi-host and phosphor-ipmi-net is not sutable for x86-power-control. Could you do me a favor, what's the problem?

**Comment by OguzhanCaglar** [comment]
Hi linlin4426,

I have the same problems too. How did you fix this?

**Comment by zhangjian3032** [comment]
@OguzhanCaglar @linlin4426 I don't know what settings services you are used,  for intel's settings service, https://github.com/Intel-BMC/settings/blob/master/include/defaults.hpp#L332, and if you are used https://github.com/openbmc/phosphor-settingsd, you can flow the guide to Create a similar interface.

anyway, this is just provide a interface to set/get the ACBoot property, how to update it, you can see https://github.com/Intel-BMC/openbmc/blob/7cf0c1cd0ce835d1833509b7b911e8a97380278b/meta-openbmc-mods/meta-common/recipes-core/ac-boot-check/ac-boot-check/ac-boot-check.sh

**Comment by zhangjian3032** [comment]
@OguzhanCaglar  if you don't care the ACBoot , you can disable this function with https://github.com/openbmc/x86-power-control/blob/99e8f9dfe6ed99e201f5920c512587fe3af3cdb9/meson_options.txt#L5

**Comment by OguzhanCaglar** [comment]
Thank you, I use the Aspeed-SDK: https://github.com/AspeedTech-BMC/openbmc. My server motherboard has Intel Xeon CPU. Had I better use the Intel-BMC SDK to work with this CPU? Cause I use phosphor-settingsd and not use Intel-BMC settings.

**Comment by zhangjian3032** [comment]
@OguzhanCaglar maybe I think, if you are used  phosphor-settingsd, create a  similar interface is fine

**Comment by vijaysai** [comment]
How can we create similar interfaces, can you kindly provide any example for this.
